//{$Id$}

{$H+}{$MODE OBJFPC}
program pwserver;

{ simple HTTP test server for FPC webserver unit					}
{ based on pswebserver (c) by Vladimir Sibirov 						}
{ modified by Hartmut Eilers <hartmut@eilers.net> 					}

{ (c) 2006 by Hartmut Eilers < hartmut@eilers.net					}
{ distributed  under the terms of the GNU GPL V 2					}
{ see http://www.gnu.org/licenses/gpl.html for details				}



uses crt, webserver;

const 	BLOCKED=true;
var
	Seite,
	SeitenStart,
	SeitenEnde,
	Counter	: AnsiString;
	cnt	: word;


procedure embeddedWeb;
var
	laber	: string;
{ every time the special URL is called this procedure generates 	}
{ some dynamic content, delivered to the browser					}
begin
	SeitenStart:='<html><body>embedded special data:';
	SeitenEnde:=' <br><a href=/index.html>back</a></body></html>';
	laber:='<br>Data I last got via HTTP:'+GetParams+'<br>';
	Seite:=SeitenStart+Counter+laber+SeitenEnde;
	writeln('embeddedWeb:>Sending Page');
	SendPage(Seite);
	writeln('embeddedWeb:>Page Send, finished');
end;

procedure embeddedWebReadParams;
var Url,Params :string;
begin
	Url:=GetURL;
	Params:=GetParams;
	writeln('embeddedWeb:> Got Parameters');
	writeln('URL=',Url,' Parameters=',Params);
end;

begin
	{ start the webserver with IP, Port, Document Root and Logfile }
	start_server('127.0.0.1',10080,BLOCKED,'./docroot/','./pwserver.log');
	{ register special URL for content generated by this program }
	SetupSpecialURL('/status/index.html',@embeddedWeb );
	SetupVariableHandler(@embeddedWebReadParams);

	cnt:=0;
	Counter:='0';
	
	// Main loop doing the real stuff for the program
	repeat
		{ process the incomming requests }
		serve_request;
		delay(100); { this is was the real prpgram does: wainting and counting :) }
		inc(cnt);
		str(cnt,Counter);
	until keypressed;
	stop_server; // stop the webserver
end.




