# make Documentation
#
# Copyright (c) 1999-2009 by Hartmut Eilers
# 
# Just do a "make all", and, when you're finished, a make clean. 

build:
	-rm ../build/OpenLabDocs/*
	-cp  LabTools-UserGuide.pdf ../build/OpenLabDocs/
